import logo from './logo.svg'
import box from './box.svg'
import category from './category.svg'
import moon from './moon.svg'
import profile from './profile-2user.svg'
import trendUp from './trend-up.svg'
import settings from './setting-2.svg'
import infoCircle from './info-circle.svg'
import brightness from './brightness.svg'
import logout from './logout.svg'
import discount from './discount-shape.svg'
import arrowRight from './arrow-right.svg'
import calendar from './calendar.svg'
import bell from './bell.svg'
import search from './search.svg'
import userImage from './user.jpeg'
import arrowDown from './arrowDown.svg'
import greenTrend from './green-uptrend.svg'
import downTrend from './downTrend.svg'
import order from './order.svg'
import refund from './refund.svg'
import cart from './shopping-cart.svg'
import income from './coin.svg'
import ArrowDown from './ArrowAdown.svg'
import greenChart from './greenCgart.svg'
import redChart from './redChart.svg'

export { redChart, greenChart, arrowRight, arrowDown, ArrowDown, userImage, bell, calendar, box, logo, discount, category, moon, logout, trendUp, search, settings, profile, infoCircle, brightness, greenTrend, refund, order, cart, income, downTrend };